baseURL = "https://blog.jethro.dev/"
languageCode = "en-us"
title = "Jethro Kuan"
theme = "er"

[params]
showTagCloud = false
description = ""
email = "jethrokuan95@gmail.com"

[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4
