baseURL = "https://blog.jethro.dev/"
languageCode = "en-us"
title = "Jethro Kuan"

theme = "elementary"

[params]
author = "Jethro Kuan"
email = "jethrokuan95@gmail.com"

[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

[menu]
[[menu.main]]
[[menu.main]]
    name = "about me"
    url = "https://www.jethro.dev"
    weight = -210
    
  [[menu.main]]
    name = "twitter"
    url = "https://twitter.com/jethroksy"
    weight = -110

  [[menu.main]]
    name = "github"
    url = "https://github.com/jethrokuan"
    weight = -100

  [[menu.main]]
    name = "linkedin"
    url = "https://linkedin.com/in/jethrokuan"
    weight = -90